# Dockerfile
FROM python:3.9-alpine

# Set a working directory in the container
WORKDIR /app

# Copy our Python script to the container
COPY app.py .

# Command to run our script
CMD ["python", "app.py"]